### PR TITLE
use `python-xlib` instead of parsing xrandr output

### LINKED ISSUE #202: Monitor names are swapped on X11
**Describe the bug**

I have 2 monitors connected, HDMI-0 and DP-0.

```
❯ xrandr | rg " connected "
HDMI-0 connected 1080x1920+2560+0 right (normal left inverted right x axis y axis) 527mm x 296mm
DP-0 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
```

image

**The above screenshot was captured on DP-0, the 2560x1440 one.**
For some reason, the monitor names seem to be swapped with each other.
When I set a wallpaper for HDMI-0 it is applied to DP-0 and vice versa.

```
❯ xrandr --output HDMI-0 --off
❯ xrandr | rg " connected "
HDMI-0 connected (normal left inverted right x axis y axis)
DP-0 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
```

image

If I disable HDMI-0 and have only DP-0 enabled, only HDMI-0 is shown in Azote.
And of course, it is actually linked with DP-0.

I have yet to test what happens if I plug in 3 monitors because I don't have a third one.
Perhaps is there an off-by-one indexing error for getting the monitor names?

**Desktop (please complete the following information):**
 - Linux distribution: Arch
 - WM: Qtile (X11)

**Azote version (please state it clearly if you use -git version):**
 - 1.13.1

### PR DESCRIPTION
**Pull request by WieeRd**
Tada

image

Fixes #202

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Well done, thank you.

**Comment by nwg-piotr** [comment]
I should have checked on openbox earlier. What you've done swaps the left and right out of my 3 displays. Sorting them by x, y helps, but I'm afraid it won't work on your setup. :)

```python
        try:
            display = display.Display()
            root = display.screen().root
            displays = [
                {'name': display.get_atom_name(m.name),
                 'x': m.x,
                 'y': m.y,
                 'width': m.width_in_pixels,
                 'height': m.height_in_pixels,
                 'xrandr-idx': i}
                for i, m in enumerate(root.xrandr_get_monitors().monitors)
            ]
            displays = sorted(displays, key=lambda x: (x.get('x'), x.get('y')))
            return displays
```

Could you check?

**Comment by WieeRd** [comment]
@nwg-piotr By "swaps the left and right", do you mean the monitor names and the wallpapers being set no longer correspond to each other, or just that the order of monitor handles in Azote does not correspond to the left-to-right arrangement of `arandr` settings?

**Comment by WieeRd** [comment]
Fortunately the latter was the case, and it is correctly fixed by adding `sorted()` (works on my setup too)

> but I'm afraid it won't work on your setup. 

I was also worried if sorting them would result in wallpapers being swapped again. 
But looks like the order of arguments passed to `feh` depends on the previously saved `xrandr-idx` key, so the order of displays in the list returned by `tools.check_displays()` doesn't matter.

https://github.com/nwg-piotr/azote/blob/d8b0bbf21338d9b4a1da0b210a200aec89168182/azote/main.py#L507-L511

Funny how I repeated the same mistake you made years ago. By coincident, the `xrandr` output was always aligned with `xrandr --listmonitors` output on your setup, and you never realized #202. Now I completely forgot about sorting by coordinates part because I haven't thought of swapping the monitor arrangement while testing. It's so hard to properly test tools that directly face the outer environment and cannot be isolated in a nice and controlled unit tests...

**Comment by nwg-piotr** [comment]
Actually I haven't tested the program much on X11. I wrote it as a nitrogen replacement for use with sway.

**Comment by WieeRd** [comment]
I guess I'll have to work on X11 things by myself or start peaking at wayland things.

Shall I send a followup PR or do you already have the patch ready?

**Comment by WieeRd** [comment]
Might as well

**Comment by nwg-piotr** [comment]
> Shall I send a followup PR or do you already have the patch ready?

Got it in PyCharm at home, not yet committed. You may do it or wait for me to get back home, as you wish :)

> I guess I'll have to work on X11 things by myself or start peaking at wayland things.

If it comes to X11, I no longer use it, though I keep a working openbox session just in case. As for Wayland, all the [nwg-shell](https://nwg-piotr.github.io/nwg-shell) project needs good contributors.

**Pull request merged**
